version: '3.3'

services:
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb_data_ferrytix:/bitnami/mongodb
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_PORT_NUMBER=${MONGODB_PORT}
  ferrytix:
    container_name: ferrytix_api
    image: ferrytix_api
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mongodb
    volumes:
      - ${HOST_SSL_CERTIFICATE}:${APP_SSL_CERTIFICATE}
      - ${HOST_SSL_KEY}:${APP_SSL_KEY}
    environment:
      - DATABASE_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:${MONGODB_PORT}/${MONGODB_DATABASE}
      - APP_SSL_CERTIFICATE=${APP_SSL_CERTIFICATE}
      - APP_SSL_KEY=${APP_SSL_KEY}
      - APP_PORT=${APP_PORT}
      - APP_MODE=${APP_MODE}
      - SECRET=${SECRET}


volumes:
  mongodb_data_ferrytix:
