# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.payment import Payment  # noqa: F401,E501
from swagger_server import util


class FaehrCardPayment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uuid: str=None, payment: Payment=None):  # noqa: E501
        """FaehrCardPayment - a model defined in Swagger

        :param uuid: The uuid of this FaehrCardPayment.  # noqa: E501
        :type uuid: str
        :param payment: The payment of this FaehrCardPayment.  # noqa: E501
        :type payment: Payment
        """
        self.swagger_types = {
            'uuid': str,
            'payment': Payment
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'payment': 'payment'
        }
        self._uuid = uuid
        self._payment = payment

    @classmethod
    def from_dict(cls, dikt) -> 'FaehrCardPayment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FaehrCardPayment of this FaehrCardPayment.  # noqa: E501
        :rtype: FaehrCardPayment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this FaehrCardPayment.

        UUID of the FaehrCard charged.  # noqa: E501

        :return: The uuid of this FaehrCardPayment.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this FaehrCardPayment.

        UUID of the FaehrCard charged.  # noqa: E501

        :param uuid: The uuid of this FaehrCardPayment.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def payment(self) -> Payment:
        """Gets the payment of this FaehrCardPayment.


        :return: The payment of this FaehrCardPayment.
        :rtype: Payment
        """
        return self._payment

    @payment.setter
    def payment(self, payment: Payment):
        """Sets the payment of this FaehrCardPayment.


        :param payment: The payment of this FaehrCardPayment.
        :type payment: Payment
        """

        self._payment = payment
