# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ticket_class import TicketClass  # noqa: F401,E501
from swagger_server import util


class Fare(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ticket_class: TicketClass=None, fare: int=None):  # noqa: E501
        """Fare - a model defined in Swagger

        :param ticket_class: The ticket_class of this Fare.  # noqa: E501
        :type ticket_class: TicketClass
        :param fare: The fare of this Fare.  # noqa: E501
        :type fare: int
        """
        self.swagger_types = {
            'ticket_class': TicketClass,
            'fare': int
        }

        self.attribute_map = {
            'ticket_class': 'ticketClass',
            'fare': 'fare'
        }
        self._ticket_class = ticket_class
        self._fare = fare

    @classmethod
    def from_dict(cls, dikt) -> 'Fare':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Fare of this Fare.  # noqa: E501
        :rtype: Fare
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ticket_class(self) -> TicketClass:
        """Gets the ticket_class of this Fare.


        :return: The ticket_class of this Fare.
        :rtype: TicketClass
        """
        return self._ticket_class

    @ticket_class.setter
    def ticket_class(self, ticket_class: TicketClass):
        """Sets the ticket_class of this Fare.


        :param ticket_class: The ticket_class of this Fare.
        :type ticket_class: TicketClass
        """

        self._ticket_class = ticket_class

    @property
    def fare(self) -> int:
        """Gets the fare of this Fare.


        :return: The fare of this Fare.
        :rtype: int
        """
        return self._fare

    @fare.setter
    def fare(self, fare: int):
        """Sets the fare of this Fare.


        :param fare: The fare of this Fare.
        :type fare: int
        """

        self._fare = fare
