# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, newbalance: int=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param newbalance: The newbalance of this InlineResponse201.  # noqa: E501
        :type newbalance: int
        """
        self.swagger_types = {
            'newbalance': int
        }

        self.attribute_map = {
            'newbalance': 'newbalance'
        }
        self._newbalance = newbalance

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def newbalance(self) -> int:
        """Gets the newbalance of this InlineResponse201.


        :return: The newbalance of this InlineResponse201.
        :rtype: int
        """
        return self._newbalance

    @newbalance.setter
    def newbalance(self, newbalance: int):
        """Sets the newbalance of this InlineResponse201.


        :param newbalance: The newbalance of this InlineResponse201.
        :type newbalance: int
        """

        self._newbalance = newbalance
