# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RefillPaperRollCommand(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, roll_length: float=None):  # noqa: E501
        """RefillPaperRollCommand - a model defined in Swagger

        :param roll_length: The roll_length of this RefillPaperRollCommand.  # noqa: E501
        :type roll_length: float
        """
        self.swagger_types = {
            'roll_length': float
        }

        self.attribute_map = {
            'roll_length': 'rollLength'
        }
        self._roll_length = roll_length

    @classmethod
    def from_dict(cls, dikt) -> 'RefillPaperRollCommand':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RefillPaperRollCommand of this RefillPaperRollCommand.  # noqa: E501
        :rtype: RefillPaperRollCommand
        """
        return util.deserialize_model(dikt, cls)

    @property
    def roll_length(self) -> float:
        """Gets the roll_length of this RefillPaperRollCommand.


        :return: The roll_length of this RefillPaperRollCommand.
        :rtype: float
        """
        return self._roll_length

    @roll_length.setter
    def roll_length(self, roll_length: float):
        """Sets the roll_length of this RefillPaperRollCommand.


        :param roll_length: The roll_length of this RefillPaperRollCommand.
        :type roll_length: float
        """

        self._roll_length = roll_length
