# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cash_payment import CashPayment  # noqa: F401,E501
from swagger_server.models.machine_location import MachineLocation  # noqa: F401,E501
from swagger_server.models.position import Position  # noqa: F401,E501
from swagger_server import util


class TicketSaleCash(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uuid: str=None, issued_by: str=None, issued_at: datetime=None, return_valid: bool=None, _from: MachineLocation=None, cash_payment: CashPayment=None, positions: List[Position]=None, sale_counter: int=None, signature: str=None):  # noqa: E501
        """TicketSaleCash - a model defined in Swagger

        :param uuid: The uuid of this TicketSaleCash.  # noqa: E501
        :type uuid: str
        :param issued_by: The issued_by of this TicketSaleCash.  # noqa: E501
        :type issued_by: str
        :param issued_at: The issued_at of this TicketSaleCash.  # noqa: E501
        :type issued_at: datetime
        :param return_valid: The return_valid of this TicketSaleCash.  # noqa: E501
        :type return_valid: bool
        :param _from: The _from of this TicketSaleCash.  # noqa: E501
        :type _from: MachineLocation
        :param cash_payment: The cash_payment of this TicketSaleCash.  # noqa: E501
        :type cash_payment: CashPayment
        :param positions: The positions of this TicketSaleCash.  # noqa: E501
        :type positions: List[Position]
        :param sale_counter: The sale_counter of this TicketSaleCash.  # noqa: E501
        :type sale_counter: int
        :param signature: The signature of this TicketSaleCash.  # noqa: E501
        :type signature: str
        """
        self.swagger_types = {
            'uuid': str,
            'issued_by': str,
            'issued_at': datetime,
            'return_valid': bool,
            '_from': MachineLocation,
            'cash_payment': CashPayment,
            'positions': List[Position],
            'sale_counter': int,
            'signature': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'issued_by': 'issuedBy',
            'issued_at': 'issuedAt',
            'return_valid': 'returnValid',
            '_from': 'from',
            'cash_payment': 'cashPayment',
            'positions': 'positions',
            'sale_counter': 'saleCounter',
            'signature': 'signature'
        }
        self._uuid = uuid
        self._issued_by = issued_by
        self._issued_at = issued_at
        self._return_valid = return_valid
        self.__from = _from
        self._cash_payment = cash_payment
        self._positions = positions
        self._sale_counter = sale_counter
        self._signature = signature

    @classmethod
    def from_dict(cls, dikt) -> 'TicketSaleCash':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TicketSaleCash of this TicketSaleCash.  # noqa: E501
        :rtype: TicketSaleCash
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this TicketSaleCash.


        :return: The uuid of this TicketSaleCash.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this TicketSaleCash.


        :param uuid: The uuid of this TicketSaleCash.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def issued_by(self) -> str:
        """Gets the issued_by of this TicketSaleCash.


        :return: The issued_by of this TicketSaleCash.
        :rtype: str
        """
        return self._issued_by

    @issued_by.setter
    def issued_by(self, issued_by: str):
        """Sets the issued_by of this TicketSaleCash.


        :param issued_by: The issued_by of this TicketSaleCash.
        :type issued_by: str
        """

        self._issued_by = issued_by

    @property
    def issued_at(self) -> datetime:
        """Gets the issued_at of this TicketSaleCash.


        :return: The issued_at of this TicketSaleCash.
        :rtype: datetime
        """
        return self._issued_at

    @issued_at.setter
    def issued_at(self, issued_at: datetime):
        """Sets the issued_at of this TicketSaleCash.


        :param issued_at: The issued_at of this TicketSaleCash.
        :type issued_at: datetime
        """

        self._issued_at = issued_at

    @property
    def return_valid(self) -> bool:
        """Gets the return_valid of this TicketSaleCash.


        :return: The return_valid of this TicketSaleCash.
        :rtype: bool
        """
        return self._return_valid

    @return_valid.setter
    def return_valid(self, return_valid: bool):
        """Sets the return_valid of this TicketSaleCash.


        :param return_valid: The return_valid of this TicketSaleCash.
        :type return_valid: bool
        """

        self._return_valid = return_valid

    @property
    def _from(self) -> MachineLocation:
        """Gets the _from of this TicketSaleCash.


        :return: The _from of this TicketSaleCash.
        :rtype: MachineLocation
        """
        return self.__from

    @_from.setter
    def _from(self, _from: MachineLocation):
        """Sets the _from of this TicketSaleCash.


        :param _from: The _from of this TicketSaleCash.
        :type _from: MachineLocation
        """

        self.__from = _from

    @property
    def cash_payment(self) -> CashPayment:
        """Gets the cash_payment of this TicketSaleCash.


        :return: The cash_payment of this TicketSaleCash.
        :rtype: CashPayment
        """
        return self._cash_payment

    @cash_payment.setter
    def cash_payment(self, cash_payment: CashPayment):
        """Sets the cash_payment of this TicketSaleCash.


        :param cash_payment: The cash_payment of this TicketSaleCash.
        :type cash_payment: CashPayment
        """

        self._cash_payment = cash_payment

    @property
    def positions(self) -> List[Position]:
        """Gets the positions of this TicketSaleCash.


        :return: The positions of this TicketSaleCash.
        :rtype: List[Position]
        """
        return self._positions

    @positions.setter
    def positions(self, positions: List[Position]):
        """Sets the positions of this TicketSaleCash.


        :param positions: The positions of this TicketSaleCash.
        :type positions: List[Position]
        """

        self._positions = positions

    @property
    def sale_counter(self) -> int:
        """Gets the sale_counter of this TicketSaleCash.


        :return: The sale_counter of this TicketSaleCash.
        :rtype: int
        """
        return self._sale_counter

    @sale_counter.setter
    def sale_counter(self, sale_counter: int):
        """Sets the sale_counter of this TicketSaleCash.


        :param sale_counter: The sale_counter of this TicketSaleCash.
        :type sale_counter: int
        """

        self._sale_counter = sale_counter

    @property
    def signature(self) -> str:
        """Gets the signature of this TicketSaleCash.


        :return: The signature of this TicketSaleCash.
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature: str):
        """Sets the signature of this TicketSaleCash.


        :param signature: The signature of this TicketSaleCash.
        :type signature: str
        """

        self._signature = signature
