# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ticket_class import TicketClass  # noqa: F401,E501
from swagger_server import util


class WaitingPassenger(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ticket_class: TicketClass=None, waiting_since: datetime=None):  # noqa: E501
        """WaitingPassenger - a model defined in Swagger

        :param ticket_class: The ticket_class of this WaitingPassenger.  # noqa: E501
        :type ticket_class: TicketClass
        :param waiting_since: The waiting_since of this WaitingPassenger.  # noqa: E501
        :type waiting_since: datetime
        """
        self.swagger_types = {
            'ticket_class': TicketClass,
            'waiting_since': datetime
        }

        self.attribute_map = {
            'ticket_class': 'ticketClass',
            'waiting_since': 'waitingSince'
        }
        self._ticket_class = ticket_class
        self._waiting_since = waiting_since

    @classmethod
    def from_dict(cls, dikt) -> 'WaitingPassenger':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WaitingPassenger of this WaitingPassenger.  # noqa: E501
        :rtype: WaitingPassenger
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ticket_class(self) -> TicketClass:
        """Gets the ticket_class of this WaitingPassenger.


        :return: The ticket_class of this WaitingPassenger.
        :rtype: TicketClass
        """
        return self._ticket_class

    @ticket_class.setter
    def ticket_class(self, ticket_class: TicketClass):
        """Sets the ticket_class of this WaitingPassenger.


        :param ticket_class: The ticket_class of this WaitingPassenger.
        :type ticket_class: TicketClass
        """

        self._ticket_class = ticket_class

    @property
    def waiting_since(self) -> datetime:
        """Gets the waiting_since of this WaitingPassenger.


        :return: The waiting_since of this WaitingPassenger.
        :rtype: datetime
        """
        return self._waiting_since

    @waiting_since.setter
    def waiting_since(self, waiting_since: datetime):
        """Sets the waiting_since of this WaitingPassenger.


        :param waiting_since: The waiting_since of this WaitingPassenger.
        :type waiting_since: datetime
        """

        self._waiting_since = waiting_since
