/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* Payment Details for Cash Payments.
*/
export class CashPayment {
    /**
    * List of coins and bills the payment consists of.
    */
    'denominations'?: Array<number>;
    /**
    * List of coins and bills the change consists of.
    */
    'change'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "denominations",
            "baseName": "denominations",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "change",
            "baseName": "change",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CashPayment.attributeTypeMap;
    }
    
    public constructor() {
    }
}

