/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class FaehrCard {
  'uuid'?: string;
  'ownedBy'?: string;
  'balance'?: number;
  'issuedAt'?: Date;
  'issuedBy'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'uuid',
      'baseName': 'uuid',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'ownedBy',
      'baseName': 'ownedBy',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'balance',
      'baseName': 'balance',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'issuedAt',
      'baseName': 'issuedAt',
      'type': 'Date',
      'format': 'date-time'
    },
    {
      'name': 'issuedBy',
      'baseName': 'issuedBy',
      'type': 'string',
      'format': 'uuid'
    }];

  static getAttributeTypeMap() {
    return FaehrCard.attributeTypeMap;
  }

  public constructor() {
  }
}

