/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TicketClass } from './TicketClass';

/**
 * The price that tickets of a given ticket class are sold for (in cents)
 */
export class Fare {
  'ticketClass'?: TicketClass;
  'fare'?: number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'ticketClass',
      'baseName': 'ticketClass',
      'type': 'TicketClass',
      'format': ''
    },
    {
      'name': 'fare',
      'baseName': 'fare',
      'type': 'number',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return Fare.attributeTypeMap;
  }

  public constructor() {
  }
}

