/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MachineStatusTicketsSoldToday } from './MachineStatusTicketsSoldToday';
import { WaitingPassenger } from './WaitingPassenger';

/**
 * The status of a machine, generated partly by the backend
 */
export class MachineStatus {
  'vending'?: boolean;
  'batteryCharge'?: number;
  'estimatedReceiptPaperFillLevel'?: number;
  'receiptPaperRollLength'?: number;
  'cpuTemperature'?: number;
  'ticketsSoldToday'?: MachineStatusTicketsSoldToday;
  'volumeOfSalesToday'?: number;
  'waiting'?: Array<WaitingPassenger>;
  /**
   * Current sale counter. Each vending machine has its own counter, that increases when a sale (TicketSale or TopUp) is completed. The sale counter can't be changed from the outside.
   */
  'saleCounter'?: number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'vending',
      'baseName': 'vending',
      'type': 'boolean',
      'format': ''
    },
    {
      'name': 'batteryCharge',
      'baseName': 'batteryCharge',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'estimatedReceiptPaperFillLevel',
      'baseName': 'estimatedReceiptPaperFillLevel',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'receiptPaperRollLength',
      'baseName': 'receiptPaperRollLength',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'cpuTemperature',
      'baseName': 'cpuTemperature',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'ticketsSoldToday',
      'baseName': 'ticketsSoldToday',
      'type': 'MachineStatusTicketsSoldToday',
      'format': ''
    },
    {
      'name': 'volumeOfSalesToday',
      'baseName': 'volumeOfSalesToday',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'waiting',
      'baseName': 'waiting',
      'type': 'Array<WaitingPassenger>',
      'format': ''
    },
    {
      'name': 'saleCounter',
      'baseName': 'saleCounter',
      'type': 'number',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return MachineStatus.attributeTypeMap;
  }

  public constructor() {
  }
}

