/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Fare } from './Fare';

/**
 * Object to hold configuration for vending machines, data that can be changed by admins
 */
export class MachineConfiguration {
  /**
   * The machine id for which to apply these settings. May be left empty in a POST request if applicable for all machines.
   */
  'forMachine'?: string;
  'maxBicycles'?: number;
  /**
   * Tolerance fot the maximal amount of passengers carrying a bicycle in the waiting area. This will determine, to what extend the maximum may be exceeded in some situations.
   */
  'maxBicyclesTolerance'?: number;
  'maxPassengers'?: number;
  /**
   * Tolerance fot the maximal amount of passengers in the waiting area. This will determine, to what extend the maximum may be exceeded in some situations.
   */
  'maxPassengersTolerance'?: number;
  'fares'?: Array<Fare>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'forMachine',
      'baseName': 'forMachine',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'maxBicycles',
      'baseName': 'maxBicycles',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'maxBicyclesTolerance',
      'baseName': 'maxBicyclesTolerance',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'maxPassengers',
      'baseName': 'maxPassengers',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'maxPassengersTolerance',
      'baseName': 'maxPassengersTolerance',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'fares',
      'baseName': 'fares',
      'type': 'Array<Fare>',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return MachineConfiguration.attributeTypeMap;
  }

  public constructor() {
  }
}

