/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PaymentMethod {
  /**
   * UUID of the FaehrCard charged.
   */
  'uuid'?: string;
  /**
   * List of coins and bills the payment consists of.
   */
  'denominations'?: Array<number>;
  /**
   * List of coins and bills the change consists of.
   */
  'change'?: Array<number>;
  'name'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'uuid',
      'baseName': 'uuid',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'denominations',
      'baseName': 'denominations',
      'type': 'Array<number>',
      'format': ''
    },
    {
      'name': 'change',
      'baseName': 'change',
      'type': 'Array<number>',
      'format': ''
    },
    {
      'name': 'name',
      'baseName': 'name',
      'type': 'string',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return PaymentMethod.attributeTypeMap;
  }

  public constructor() {
  }
}

