/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentMethod } from './PaymentMethod';

/**
 * A payment for a ticket sale.
 */
export class Payment {
  'uuid'?: string;
  'amount'?: number;
  'method'?: PaymentMethod;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'uuid',
      'baseName': 'uuid',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'amount',
      'baseName': 'amount',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'method',
      'baseName': 'method',
      'type': 'PaymentMethod',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return Payment.attributeTypeMap;
  }

  public constructor() {
  }
}

