/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Fare } from './Fare';

export class Position {
  'fare'?: Fare;
  'count'?: number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'fare',
      'baseName': 'fare',
      'type': 'Fare',
      'format': ''
    },
    {
      'name': 'count',
      'baseName': 'count',
      'type': 'number',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return Position.attributeTypeMap;
  }

  public constructor() {
  }
}

