/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StaffRole } from './StaffRole';

/**
 * Staff members work for the ferry and are granted free rides.
 */
export class StaffMember {
  'uuid'?: string;
  'firstName'?: string;
  'lastName'?: string;
  'role'?: StaffRole;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'uuid',
      'baseName': 'uuid',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'firstName',
      'baseName': 'firstName',
      'type': 'string',
      'format': ''
    },
    {
      'name': 'lastName',
      'baseName': 'lastName',
      'type': 'string',
      'format': ''
    },
    {
      'name': 'role',
      'baseName': 'role',
      'type': 'StaffRole',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return StaffMember.attributeTypeMap;
  }

  public constructor() {
  }
}

