/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class TicketClass {
  /**
   * whether or not a bicycle was carried
   */
  'bicycle'?: boolean;
  /**
   * whether or not a return trip has been purchased
   */
  '_return'?: boolean;
  /**
   * reduced fare for physically disabled persons and children under the age of 14
   */
  'reduced'?: boolean;
  /**
   * only for staff members
   */
  'staff'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'bicycle',
      'baseName': 'bicycle',
      'type': 'boolean',
      'format': ''
    },
    {
      'name': '_return',
      'baseName': 'return',
      'type': 'boolean',
      'format': ''
    },
    {
      'name': 'reduced',
      'baseName': 'reduced',
      'type': 'boolean',
      'format': ''
    },
    {
      'name': 'staff',
      'baseName': 'staff',
      'type': 'boolean',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return TicketClass.attributeTypeMap;
  }

  public constructor() {
  }
}

