/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MachineLocation } from './MachineLocation';
import { Payment } from './Payment';
import { Position } from './Position';

/**
 * A collection of tickets that are paid and used at once.
 */
export class TicketSale {
  'uuid'?: string;
  'issuedBy'?: string;
  'issuedAt'?: Date;
  'returnValid'?: boolean;
  'from'?: MachineLocation;
  'payment'?: Payment;
  'positions'?: Array<Position>;
  'saleCounter'?: number;
  'signature'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'uuid',
      'baseName': 'uuid',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'issuedBy',
      'baseName': 'issuedBy',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'issuedAt',
      'baseName': 'issuedAt',
      'type': 'Date',
      'format': 'date-time'
    },
    {
      'name': 'returnValid',
      'baseName': 'returnValid',
      'type': 'boolean',
      'format': ''
    },
    {
      'name': 'from',
      'baseName': 'from',
      'type': 'MachineLocation',
      'format': ''
    },
    {
      'name': 'payment',
      'baseName': 'payment',
      'type': 'Payment',
      'format': ''
    },
    {
      'name': 'positions',
      'baseName': 'positions',
      'type': 'Array<Position>',
      'format': ''
    },
    {
      'name': 'saleCounter',
      'baseName': 'saleCounter',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'signature',
      'baseName': 'signature',
      'type': 'string',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return TicketSale.attributeTypeMap;
  }

  public constructor() {
  }
}

