/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Payment } from './Payment';

export class TopUp {
  'uuid'?: string;
  /**
   * UUID of the FaehrCard the TopUp is for.
   */
  '_for'?: string;
  'issuedAt'?: Date;
  /**
   * The id of the vending machine that the topup has been purchased at. Is null if purchased online
   */
  'issuedBy'?: string;
  'amount'?: number;
  'paid'?: number;
  'payment'?: Payment;
  /**
   * Describes whether the top up was done when the card was issued
   */
  'initial'?: boolean;
  'saleCounter'?: number;
  'signature'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'uuid',
      'baseName': 'uuid',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': '_for',
      'baseName': 'for',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'issuedAt',
      'baseName': 'issuedAt',
      'type': 'Date',
      'format': 'date-time'
    },
    {
      'name': 'issuedBy',
      'baseName': 'issuedBy',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'amount',
      'baseName': 'amount',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'paid',
      'baseName': 'paid',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'payment',
      'baseName': 'payment',
      'type': 'Payment',
      'format': ''
    },
    {
      'name': 'initial',
      'baseName': 'initial',
      'type': 'boolean',
      'format': ''
    },
    {
      'name': 'saleCounter',
      'baseName': 'saleCounter',
      'type': 'number',
      'format': ''
    },
    {
      'name': 'signature',
      'baseName': 'signature',
      'type': 'string',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return TopUp.attributeTypeMap;
  }

  public constructor() {
  }
}

