/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MachineLocation } from './MachineLocation';

export class VendingMachine {
  'uuid'?: string;
  'publicKey'?: string;
  'location'?: MachineLocation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'uuid',
      'baseName': 'uuid',
      'type': 'string',
      'format': 'uuid'
    },
    {
      'name': 'publicKey',
      'baseName': 'publicKey',
      'type': 'string',
      'format': ''
    },
    {
      'name': 'location',
      'baseName': 'location',
      'type': 'MachineLocation',
      'format': ''
    }];

  static getAttributeTypeMap() {
    return VendingMachine.attributeTypeMap;
  }

  public constructor() {
  }
}

