/**
 * FerryTix
 * This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hendrik.lankers.hl@googlemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TicketClass } from './TicketClass';

/**
 * A passenger waiting in the waiting area
 */
export class WaitingPassenger {
  'ticketClass'?: TicketClass;
  'waitingSince'?: Date;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      'name': 'ticketClass',
      'baseName': 'ticketClass',
      'type': 'TicketClass',
      'format': ''
    },
    {
      'name': 'waitingSince',
      'baseName': 'waitingSince',
      'type': 'Date',
      'format': 'date-time'
    }];

  static getAttributeTypeMap() {
    return WaitingPassenger.attributeTypeMap;
  }

  public constructor() {
  }
}

